### PR TITLE
Add the enviornmental logger finder

### PR DESCRIPTION
**Pull request by FlyingWithJerome**
This finder will take
- date time (in the format of "month/date/year hour:min:sec"
- root_directory of the environmental logger files

It should be called in the following pattern:
```sh
python hyperspectral_flux_based_calibration.py "09/22/2016 13:53:44" /projects/arpae/terraref/sites/ua-mac/raw_data/EnvironmentLogger # This is for ROGER production
```

And the nearest two (regarding to the time) environmental logger records will be printed out to the stdout.

More details are in the docstring of the script

### CODE REVIEW

**Comment by FlyingWithJerome** [comment]
@dlebauer @czender 

I checked the environmental logger files from April, and seems that we have a little mess around there. We have the files end with "enviromentlogger.json" and the files end with "environmentlogger.json." I believe it is because of the typo, and I hope someone who has the write access to /project folder can clean them up.

Another situation is that the earlier (for example, April) loggers were collected once two minutes, and the later loggers (for example, September) were collected hourly.

**Comment by czender** [comment]
@FlyingWithJerome EL files are aggregations of individual sample times. It does not matter that the length of the aggregation has changed from 2 minutes to one hour. It's the same amount of data, right? As for the typo, yes, but please create a separate issue for that so @delbauer or @max-zilla can rename the affected files. That has nothing to do with this pull request.

**Comment by FlyingWithJerome** [comment]
@czender Done. But please do not merge right now. I just renamed the file, but the Git accidentally committed and pushed my modification on the source file as well. Right now this file is not executable because I'm updating the algorithm; it will be back soon.

**Comment by FlyingWithJerome** [comment]
@czender It now can search for the nearest two records among the EL files, extract two nearest flx_spc_dwn arrays, take their weighted average and write into an output netCDF file.

EL works 24*7 but HS only works 16 hours, so we do not need to handle the records cross days, but I still need to handle an edge case that it will take the last record from file_1 and the first record from file_2. Other than that, the script can work normally in most cases in both my home machine and ROGER.

The output netCDF file will only have two variables and one dimension:
dimension: wavelength
variables:   weighted_average_downwelling_irradiance
                   wavelength

**Comment by FlyingWithJerome** [comment]
@czender I had added the test on the output reflectance graph in the [hyperpspectral_test.py](../blob/master/hyperspectral/hyperspectral_test.py) as what we discussed yesterday. The new commandline for the hyperspectral_test.py is
```sh
python hyperspectral_test.py <input_netCDF_file> <verbosity_level> <maximum_saturated_exposure>
```
Now the test script requires a new argument "maximum_saturated_exposure," but you don't need to change the workflow.sh right now because I set maximum_saturated_exposure as a default parameter (with default value of 0) and can be overridden with the input value. This test is marked an expected failure until we finished the new calibration workflow and it can work as what we want.

**Comment by max-zilla** [comment]
issue created for correcting the typo:
https://github.com/terraref/computing-pipeline/issues/287

**Pull request merged**
